create controllers
Tobby8629/Blog_app pull request #5
Opened 2023-05-08 16:03 UTC by Tobby8629

create users and posts controller
- create the 7Restful routes using resources
- use nested resources; nesting the post resources inside the user resources
- create the User controller and it view file
- create the post controller

2023-05-08 16:05 UTC, prolajumokeoni commented
Hi @Tobby8629, Kindly fix the linter errors 👍🏿

2023-05-08 16:12 UTC, Tobby8629 commented
i fixed them, thank you very much 🙏🏽

2023-05-08 17:12 UTC, prolajumokeoni requested changes
Hi @Tobby8629 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Controllers,  Views and Route files created 👏



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 17:12 UTC, prolajumokeoni commented on app/controllers/posts_controller.rb
> +end
- [ ] In your posts_controller, please add  #index and #show actions, it's okay for the actions to be empty for now.

````ruby
 def index; end

  def show; end
````


- [ ] Kindly add corresponding view files for the index and show controller actions, for your posts controller 👍🏿

2023-05-08 17:12 UTC, prolajumokeoni commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
- [ ] In your users_controller, please add  #show actions, it's okay for the actions to be empty for now.

````ruby
  def show; end
````

- [ ] Kindly add corresponding view files for the show controller actions, you currently have only the index view file for your users controller 👍🏿

2023-05-08 17:12 UTC, prolajumokeoni commented on config/routes.rb
>  end
- [ ] Kindly configure your routes properly, so you don't expose unnecessary endpoints

```ruby
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
```

2023-05-08 17:12 UTC, prolajumokeoni requested changes
Hi @Tobby8629 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Controllers,  Views and Route files created 👏



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-08 17:12 UTC, prolajumokeoni requested changes
Hi @Tobby8629 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Controllers,  Views and Route files created 👏



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 00:23 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @Tobby8629, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 00:23 UTC, bobb-Rob commented on app/controllers/posts_controller.rb
> +class PostsController < ApplicationController
- As mentioned by the previous reviewer, Kindly add corresponding view files for the index and show controller actions, for your posts and user controller 👍🏿. I noticed you added only index.html.erb for user. Please add the show HTML.erb for users and the both index.html.erb and show.html.erb for post.

2023-05-09 01:00 UTC, Reem-lab approved these changes
Hi @Tobby8629, 🤩🔥 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/l41YmQjOz9qg2Ecow/giphy.gif"/>

## Highlights
- [ ] Great job on the functionality for set up 🚀
- [ ] Great job working in the routes✨✨
- [ ] Professional README 🔥
- [ ] Followed Gitflow 🔥

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 11:47 UTC, merged